//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drug_Details
    {
        public Drug_Details()
        {
            this.PrescriptionDrugs = new HashSet<PrescriptionDrug>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DrugTypeId { get; set; }
        public string DrugName { get; set; }
        public string DrugDescription { get; set; }
        public string GenericName { get; set; }
        public string RetailPrice { get; set; }
        public Nullable<System.DateTime> DrugAvailableDate { get; set; }
        public Nullable<System.DateTime> DrugWithdrawDate { get; set; }
        public string Note { get; set; }
        public string Extra { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> NotDeletable { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserId { get; set; }
    
        public virtual Drug_Companies Drug_Companies { get; set; }
        public virtual Drug_Type Drug_Type { get; set; }
        public virtual ICollection<PrescriptionDrug> PrescriptionDrugs { get; set; }
    }
}
