//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalTest
    {
        public MedicalTest()
        {
            this.PrescriptionMedicalTests = new HashSet<PrescriptionMedicalTest>();
        }
    
        public int Id { get; set; }
        public string MedicalTestName { get; set; }
        public string MedicalTestDetails { get; set; }
        public string MedicalTestAdvice { get; set; }
        public string Note { get; set; }
        public string Extra { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> NotDeletable { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
    
        public virtual ICollection<PrescriptionMedicalTest> PrescriptionMedicalTests { get; set; }
    }
}
