//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrescriptionManagementDBEntities : DbContext
    {
        public PrescriptionManagementDBEntities()
            : base("name=PrescriptionManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MedicalTest> MedicalTests { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<DoctorChember> DoctorChembers { get; set; }
        public virtual DbSet<Drug_Companies> Drug_Companies { get; set; }
        public virtual DbSet<Drug_Details> Drug_Details { get; set; }
        public virtual DbSet<Drug_Type> Drug_Type { get; set; }
        public virtual DbSet<Prescription> Prescriptions { get; set; }
        public virtual DbSet<PrescriptionDrug> PrescriptionDrugs { get; set; }
        public virtual DbSet<PrescriptionMedicalTest> PrescriptionMedicalTests { get; set; }
        public virtual DbSet<Advice> Advices { get; set; }
    }
}
